---
AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda for DynamoDB Create Table
Resources:
  IamRoleLambdaExecution:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: 'lambda-dynamodb-crud-lambdaPolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*

              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                  - dynamodb:DescribeTable
                Resource:
                  - Fn::Sub: arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/*
      Path: "/"
      RoleName: 'lambda-dynamodb-crud-lambdaRole'
  LambdaFunctionWithCF:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: 'serverless.barackka'
        S3Key: lambda-dynamodb-crud-0.0.1-SNAPSHOT.jar
      FunctionName: lambda-dynamodb-crud
      Handler: tech.heartin.books.serverlesscookbook.MyDynamoDbCrudHandler::handleRequest
      MemorySize: 512
      Role: !GetAtt IamRoleLambdaExecution.Arn
      Runtime: java8
      Timeout: 15
    DependsOn:
      - IamRoleLambdaExecution


  DynamoDbCrudApi:
    Type: AWS::ApiGateway::RestApi
    DependsOn:
      - LambdaFunctionWithCF
    Properties:
      Name: Greeting API Lambda Combination
      Description: API for greeting an user
      FailOnWarnings: true

  DynamoDbCrudResource:
    Type: AWS::ApiGateway::Resource
    DependsOn:
      - DynamoDbCrudApi
    Properties:
      RestApiId: !Ref DynamoDbCrudApi
      ParentId: !GetAtt DynamoDbCrudApi.RootResourceId
      PathPart: 'dynamoDbCrud'

  MyPutMethod:
    Type: AWS::ApiGateway::Method
    DependsOn:  DynamoDbCrudResource
    Properties:
      AuthorizationType: NONE
      HttpMethod: POST
      Integration:
        Type: AWS
        IntegrationHttpMethod: POST
        IntegrationResponses:
          - StatusCode: 200
        Uri:  !Sub  'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaFunctionWithCF.Arn}/invocations'
      ResourceId: !Ref DynamoDbCrudResource
      RestApiId: !Ref DynamoDbCrudApi
      MethodResponses:
        - StatusCode: 200

  MyDeployment:
    DependsOn: MyPutMethod
    Type: AWS::ApiGateway::Deployment
    Properties:
      Description: 'First API with Lambda and DynamoDB'
      RestApiId: !Ref DynamoDbCrudApi
      StageDescription:
        Description: 'Dev Stage'
      StageName: 'dev'

  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    DependsOn: MyPutMethod
    Properties:
      FunctionName: !GetAtt LambdaFunctionWithCF.Arn # !Ref LambdaFunctionWithCF   - is ok
      Action: 'lambda:InvokeFunction'
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub
        - arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${API_ID}/*/POST/dynamoDbCrud
        - API_ID: !Ref DynamoDbCrudApi

Outputs:
  SampleEndpoint:
    Description: 'DynamoDB CRUD Endpoint'
    Value: !Sub
      - https://${API_ID}.execute-api.${AWS::Region}.amazonaws.com/dev/dynamoDbCrud
      - API_ID: !Ref DynamoDbCrudApi
